// Generated by https://quicktype.io

export interface MetaData {
    app: string;
    appVersion: string;
    compatibilityVersion: number;
    created: Created;
    fonts: any[];
    pagesAndArtboards: { [key: string]: PageMetaData };
    variant: string;
    version: number;
}

interface PageMetaData {
    name: string;
    artboards: { [key: string]: ArtboardMetaData }
}

export interface ArtboardMetaData {
    name: string;
}

export interface Created {
    app: string;
    appVersion: string;
    compatibilityVersion: number;
    variant: string;
    version: number;
}
